- name: Configuring LoadBalancer
  hosts: loadbalancer
  tasks: 
  - name: Install haproxy package
    package:
      name: haproxy
      state: present

  - name: Copy haproxy config File
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: "0644"
    notify: Restart haproxy LB Service

  - name: Start haproxy LB Service
    service:
      name: haproxy
      state: started

  handlers:
  - name: Restart haproxy LB Service
    service:
      name: haproxy
      state: restarted


- name: Configuring Webserver
  hosts: webserver
  tasks:
  - name: Installing HTTPD Webserver
    package: 
      name: httpd
      state: present
    register: httpd_install

  - name: Start HTTPD Service
    service:
      name: "httpd"
      state: started
    failed_when: "httpd_install.rc != 0"

  - name: Copy WebPages
    template:
      src: webpage.j2
      dest: /var/www/html/index.html
